### PR TITLE
Merge changes from 'staging' to 'main' (Update Image Tags for github-repository-dispatcher-service2)

### PR DESCRIPTION
**Pull request by ujala-singh**
## Summary

Description, Jira Ticket Links and PR Links Fields are mandatory.
---
### Description

- Image Tag Update: "github-repository-dispatcher-service2"
- Image Tag Update: "github-repository-dispatcher-service2"
- Image Tag Update: "github-repository-dispatcher-service2"
- This will eventually decreases the effort to track the changes which are going to the production as it collates all the information on a slack channel.

### Jira Ticket Links
-  https://ujala-singh.atlassian.net/browse/PLOAT-25
### PR Links
- PR Owner: @ism2015, PR Link: https://github.com/ujala-singh/github-repository-dispatcher-service2/pull/7
- https://github.com/ujala-singh/github-repository-dispatcher-service2/pull/6
- https://github.com/ujala-singh/github-repository-dispatcher-service2/pull/5

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code refactoring (restructing existing code without changing any functionality)
- [ ] This change requires a documentation update

## Testing Checklist

Changes tested on
- [ ] staging (pre-prod)
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

### CODE REVIEW

**Comment by ujala-singh** [comment]
Hey @ism2015, your main branch PR has been automatically created. In order to merge the PR, Please test your changes on staging (pre-prod) and update the change summary and checks accordingly (Don't forget to add the JIRA Ticket).

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description, Jira Ticket Links
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
Hey @ujala-singh, your main branch PR has been automatically created. In order to merge the PR, Please test your changes on staging (pre-prod) and update the change summary and checks accordingly (Don't forget to add the JIRA Ticket).

**Comment by ujala-singh** [comment]
A new commit has been added to the pull request, indicating an update to the image tag. Before proceeding, please ensure thorough testing of these changes in the staging (Pre-Prod) environment. Mark the testing checklist below accordingly:

## Testing Checklist

Changes tested on
- [ ] development
- [ ] production
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description, Jira Ticket Links
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description, Jira Ticket Links
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description, Jira Ticket Links
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
A new commit has been added to the pull request, indicating an update to the image tag. Before proceeding, please ensure thorough testing of these changes in the staging (Pre-Prod) environment. Mark the testing checklist below accordingly:

## Testing Checklist

Changes tested on
- [ ] development
- [ ] production
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
A new commit has been added to the pull request, indicating an update to the image tag. Before proceeding, please ensure thorough testing of these changes in the staging (Pre-Prod) environment. Mark the testing checklist below accordingly:

## Testing Checklist

Changes tested on
- [ ] development
- [ ] production
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

**Review by ism2015 — APPROVED** [review]

**Pull request merged**
