### PR TITLE
Merge changes from 'staging' to 'main' (Update Image Tags for github-repository-dispatcher-service3)

### PR DESCRIPTION
**Pull request by ujala-singh**
### Description

- Image Tag Update: "github-repository-dispatcher-service3"
- This PR is adding feature to handle test cases automatically and running test cases in CI pipeline.
- This will enable automatic releases to production and reduce release time.

### Jira Ticket Links
- https://ujala-singh.atlassian.net/browse/PLOAT-25

### PR Links
- https://github.com/ujala-singh/github-repository-dispatcher-service3/pull/2
- https://github.com/ujala-singh/github-repository-dispatcher-service3/pull/1

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code refactoring (restructing existing code without changing any functionality)
- [ ] This change requires a documentation update

## Testing Checklist

Changes tested on
- [x] staging (pre-prod)
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

### CODE REVIEW

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description, Jira Ticket Links
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
A new commit has been added to the pull request, indicating an update to the image tag. Before proceeding, please ensure thorough testing of these changes in the staging (Pre-Prod) environment. Mark the testing checklist below accordingly:

## Testing Checklist

Changes tested on
- [ ] development
- [ ] production
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

**Review by jolly3697 — APPROVED** [review]

**Pull request merged**
