### PR TITLE
Merge changes from 'staging' to 'main' (Update Image Tags for github-repository-dispatcher-service2)

### PR DESCRIPTION
**Pull request by ujala-singh**
## Summary

Description, Jira Ticket Links and PR Links Fields are mandatory.
---
### Description

- Image Tag Update:- "github-repository-dispatcher-service2"
- Image Tag Update: github-repository-dispatcher-service2
- This will eventually decreases the effort to track the changes which are going to the production as it collates all the information on a slack channel.

### Jira Ticket Links
- https://ujala-singh.atlassian.net/browse/PLOAT-25

### PR Links
- PR Owner:- @ujala-singh, Microservice PR Link:- https://github.com/ujala-singh/github-repository-dispatcher-service2/pull/8

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code refactoring (restructing existing code without changing any functionality)
- [ ] This change requires a documentation update

## Testing Checklist

Changes tested on
- [ ] staging (pre-prod)
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

### CODE REVIEW

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description, Jira Ticket Links
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Review by jolly3697 — DISMISSED** [review]

**Comment by ujala-singh** [comment]
A new commit has been added to the pull request, indicating an update to the image tag. Before proceeding, please ensure thorough testing of these changes in the staging (Pre-Prod) environment. Mark the testing checklist below accordingly:

## Testing Checklist

Changes tested on
- [ ] development
- [ ] production
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

**Review by jolly3697 — APPROVED** [review]

**Comment by ujala-singh** [comment]
Required Checks have failed for this PR. Please fix the issues before merging.

**Comment by ujala-singh** [comment]
The required check 'check_fields' has failed.\nCheck URL: https://github.com/ujala-singh/github-repository-dispatch-receiver/actions/runs/9028932293/job/24810284504

**Comment by ujala-singh** [comment]
The required check  has failed. Please fix the issues before approving the PR.
        Check URL: https://github.com/ujala-singh/github-repository-dispatch-receiver/actions/runs/9028932293/job/24810284504

**Comment by ujala-singh** [comment]
The required check 'check_fields' has failed. Please fix the issues before approving the PR.
        Check URL: https://github.com/ujala-singh/github-repository-dispatch-receiver/actions/runs/9028932293/job/24810284504

**Comment by ujala-singh** [comment]
The required check 'check_fields' has failed. Please fix the issues before approving the PR.
        Check URL: https://github.com/ujala-singh/github-repository-dispatch-receiver/actions/runs/9028932293/job/24810284504

**Comment by ujala-singh** [comment]
The required check 'check_fields' has failed. Please fix the issues before approving the PR.
        Check URL: https://github.com/ujala-singh/github-repository-dispatch-receiver/actions/runs/9028932293/job/24810284504

**Review by jolly3697 — DISMISSED** [review]

**Review by jolly3697 — DISMISSED** [review]

**Review by jolly3697 — DISMISSED** [review]

**Comment by ujala-singh** [comment]
Error: The following fields are empty: Description, Jira Ticket Links
---
**Hint:** Pull Request description is too short. Please add relevant information about the changes.

**Comment by ujala-singh** [comment]
A new commit has been added to the pull request, indicating an update to the image tag. Before proceeding, please ensure thorough testing of these changes in the staging (Pre-Prod) environment. Mark the testing checklist below accordingly:

## Testing Checklist

Changes tested on
- [ ] development
- [ ] production
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

**Review by jolly3697 — APPROVED** [review]

**Comment by ujala-singh** [comment]
A new commit has been added to the pull request, indicating an update to the image tag. Before proceeding, please ensure thorough testing of these changes in the staging (Pre-Prod) environment. Mark the testing checklist below accordingly:

## Testing Checklist

Changes tested on
- [ ] development
- [ ] production
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

**Review by jolly3697 — APPROVED** [review]

**Review by jolly3697 — APPROVED** [review]

**Review by jolly3697 — APPROVED** [review]

**Comment by ujala-singh** [comment]
A new commit has been added to the pull request, indicating an update to the image tag. Before proceeding, please ensure thorough testing of these changes in the staging (Pre-Prod) environment. Mark the testing checklist below accordingly:

## Testing Checklist

Changes tested on
- [ ] development
- [ ] production
- [ ] [MABL Tests Link]() (if any)
- [ ] [Successful Workflow Links]() (if any)

**Review by jolly3697 — APPROVED** [review]

**Pull request merged**
